// Copyright © 2023 OpenIM open source community. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: common/common.proto

package common

import (
	wrapperspb "github.com/SupersStone/new-protocol/wrapperspb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserFullInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserID             string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Password           string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Account            string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	PhoneNumber        string                 `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	AreaCode           string                 `protobuf:"bytes,5,opt,name=areaCode,proto3" json:"areaCode,omitempty"`
	Email              string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Nickname           string                 `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`
	FaceURL            string                 `protobuf:"bytes,8,opt,name=faceURL,proto3" json:"faceURL,omitempty"`
	Gender             int32                  `protobuf:"varint,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Level              int32                  `protobuf:"varint,10,opt,name=level,proto3" json:"level,omitempty"`
	Birth              int64                  `protobuf:"varint,11,opt,name=birth,proto3" json:"birth,omitempty"`
	AllowAddFriend     int32                  `protobuf:"varint,12,opt,name=allowAddFriend,proto3" json:"allowAddFriend,omitempty"`
	AllowBeep          int32                  `protobuf:"varint,13,opt,name=allowBeep,proto3" json:"allowBeep,omitempty"`
	AllowVibration     int32                  `protobuf:"varint,14,opt,name=allowVibration,proto3" json:"allowVibration,omitempty"`
	GlobalRecvMsgOpt   int32                  `protobuf:"varint,15,opt,name=globalRecvMsgOpt,proto3" json:"globalRecvMsgOpt,omitempty"`
	RegisterType       int32                  `protobuf:"varint,16,opt,name=registerType,proto3" json:"registerType,omitempty"`
	SurName            string                 `protobuf:"bytes,17,opt,name=surName,proto3" json:"surName,omitempty"`
	Name               string                 `protobuf:"bytes,18,opt,name=name,proto3" json:"name,omitempty"`
	QrcodeUrl          string                 `protobuf:"bytes,19,opt,name=qrcodeUrl,proto3" json:"qrcodeUrl,omitempty"`
	PublicKey          string                 `protobuf:"bytes,20,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Address            string                 `protobuf:"bytes,21,opt,name=address,proto3" json:"address,omitempty"`
	IsContact          int32                  `protobuf:"varint,22,opt,name=isContact,proto3" json:"isContact,omitempty"`
	IsBlocked          int32                  `protobuf:"varint,23,opt,name=isBlocked,proto3" json:"isBlocked,omitempty"`
	AutoDeleteMsg      int32                  `protobuf:"varint,24,opt,name=autoDeleteMsg,proto3" json:"autoDeleteMsg,omitempty"`
	AutoDeleteDuration int32                  `protobuf:"varint,25,opt,name=autoDeleteDuration,proto3" json:"autoDeleteDuration,omitempty"`
	OnlineStatus       int32                  `protobuf:"varint,26,opt,name=onlineStatus,proto3" json:"onlineStatus,omitempty"`
	OfflineAt          int32                  `protobuf:"varint,27,opt,name=offlineAt,proto3" json:"offlineAt,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserFullInfo) Reset() {
	*x = UserFullInfo{}
	mi := &file_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFullInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFullInfo) ProtoMessage() {}

func (x *UserFullInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFullInfo.ProtoReflect.Descriptor instead.
func (*UserFullInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *UserFullInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserFullInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserFullInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserFullInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserFullInfo) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *UserFullInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserFullInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserFullInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *UserFullInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserFullInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserFullInfo) GetBirth() int64 {
	if x != nil {
		return x.Birth
	}
	return 0
}

func (x *UserFullInfo) GetAllowAddFriend() int32 {
	if x != nil {
		return x.AllowAddFriend
	}
	return 0
}

func (x *UserFullInfo) GetAllowBeep() int32 {
	if x != nil {
		return x.AllowBeep
	}
	return 0
}

func (x *UserFullInfo) GetAllowVibration() int32 {
	if x != nil {
		return x.AllowVibration
	}
	return 0
}

func (x *UserFullInfo) GetGlobalRecvMsgOpt() int32 {
	if x != nil {
		return x.GlobalRecvMsgOpt
	}
	return 0
}

func (x *UserFullInfo) GetRegisterType() int32 {
	if x != nil {
		return x.RegisterType
	}
	return 0
}

func (x *UserFullInfo) GetSurName() string {
	if x != nil {
		return x.SurName
	}
	return ""
}

func (x *UserFullInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserFullInfo) GetQrcodeUrl() string {
	if x != nil {
		return x.QrcodeUrl
	}
	return ""
}

func (x *UserFullInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *UserFullInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserFullInfo) GetIsContact() int32 {
	if x != nil {
		return x.IsContact
	}
	return 0
}

func (x *UserFullInfo) GetIsBlocked() int32 {
	if x != nil {
		return x.IsBlocked
	}
	return 0
}

func (x *UserFullInfo) GetAutoDeleteMsg() int32 {
	if x != nil {
		return x.AutoDeleteMsg
	}
	return 0
}

func (x *UserFullInfo) GetAutoDeleteDuration() int32 {
	if x != nil {
		return x.AutoDeleteDuration
	}
	return 0
}

func (x *UserFullInfo) GetOnlineStatus() int32 {
	if x != nil {
		return x.OnlineStatus
	}
	return 0
}

func (x *UserFullInfo) GetOfflineAt() int32 {
	if x != nil {
		return x.OfflineAt
	}
	return 0
}

type ContactFullInfo struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	UserID           string                  `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Password         string                  `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Account          string                  `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	PhoneNumber      string                  `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	AreaCode         string                  `protobuf:"bytes,5,opt,name=areaCode,proto3" json:"areaCode,omitempty"`
	Email            string                  `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Nickname         string                  `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`
	FaceURL          string                  `protobuf:"bytes,8,opt,name=faceURL,proto3" json:"faceURL,omitempty"`
	Gender           int32                   `protobuf:"varint,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Level            int32                   `protobuf:"varint,10,opt,name=level,proto3" json:"level,omitempty"`
	Birth            int64                   `protobuf:"varint,11,opt,name=birth,proto3" json:"birth,omitempty"`
	AllowAddFriend   int32                   `protobuf:"varint,12,opt,name=allowAddFriend,proto3" json:"allowAddFriend,omitempty"`
	AllowBeep        int32                   `protobuf:"varint,13,opt,name=allowBeep,proto3" json:"allowBeep,omitempty"`
	AllowVibration   int32                   `protobuf:"varint,14,opt,name=allowVibration,proto3" json:"allowVibration,omitempty"`
	GlobalRecvMsgOpt int32                   `protobuf:"varint,15,opt,name=globalRecvMsgOpt,proto3" json:"globalRecvMsgOpt,omitempty"`
	RegisterType     int32                   `protobuf:"varint,16,opt,name=registerType,proto3" json:"registerType,omitempty"`
	SurName          string                  `protobuf:"bytes,17,opt,name=surName,proto3" json:"surName,omitempty"`
	Name             string                  `protobuf:"bytes,18,opt,name=name,proto3" json:"name,omitempty"`
	QrcodeUrl        string                  `protobuf:"bytes,19,opt,name=qrcodeUrl,proto3" json:"qrcodeUrl,omitempty"`
	PublicKey        string                  `protobuf:"bytes,20,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	IsBlocked        bool                    `protobuf:"varint,21,opt,name=isBlocked,proto3" json:"isBlocked,omitempty"`
	Address          string                  `protobuf:"bytes,22,opt,name=address,proto3" json:"address,omitempty"`
	OnlineStatus     int32                   `protobuf:"varint,23,opt,name=onlineStatus,proto3" json:"onlineStatus,omitempty"`
	OfflineAt        *wrapperspb.Int32Value  `protobuf:"bytes,24,opt,name=offlineAt,proto3" json:"offlineAt,omitempty"`
	RemarkName       *wrapperspb.StringValue `protobuf:"bytes,25,opt,name=remarkName,proto3" json:"remarkName,omitempty"`
	RemarkSurname    *wrapperspb.StringValue `protobuf:"bytes,26,opt,name=remarkSurname,proto3" json:"remarkSurname,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContactFullInfo) Reset() {
	*x = ContactFullInfo{}
	mi := &file_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactFullInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFullInfo) ProtoMessage() {}

func (x *ContactFullInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFullInfo.ProtoReflect.Descriptor instead.
func (*ContactFullInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *ContactFullInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ContactFullInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ContactFullInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ContactFullInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ContactFullInfo) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *ContactFullInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactFullInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ContactFullInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *ContactFullInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *ContactFullInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ContactFullInfo) GetBirth() int64 {
	if x != nil {
		return x.Birth
	}
	return 0
}

func (x *ContactFullInfo) GetAllowAddFriend() int32 {
	if x != nil {
		return x.AllowAddFriend
	}
	return 0
}

func (x *ContactFullInfo) GetAllowBeep() int32 {
	if x != nil {
		return x.AllowBeep
	}
	return 0
}

func (x *ContactFullInfo) GetAllowVibration() int32 {
	if x != nil {
		return x.AllowVibration
	}
	return 0
}

func (x *ContactFullInfo) GetGlobalRecvMsgOpt() int32 {
	if x != nil {
		return x.GlobalRecvMsgOpt
	}
	return 0
}

func (x *ContactFullInfo) GetRegisterType() int32 {
	if x != nil {
		return x.RegisterType
	}
	return 0
}

func (x *ContactFullInfo) GetSurName() string {
	if x != nil {
		return x.SurName
	}
	return ""
}

func (x *ContactFullInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactFullInfo) GetQrcodeUrl() string {
	if x != nil {
		return x.QrcodeUrl
	}
	return ""
}

func (x *ContactFullInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ContactFullInfo) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *ContactFullInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ContactFullInfo) GetOnlineStatus() int32 {
	if x != nil {
		return x.OnlineStatus
	}
	return 0
}

func (x *ContactFullInfo) GetOfflineAt() *wrapperspb.Int32Value {
	if x != nil {
		return x.OfflineAt
	}
	return nil
}

func (x *ContactFullInfo) GetRemarkName() *wrapperspb.StringValue {
	if x != nil {
		return x.RemarkName
	}
	return nil
}

func (x *ContactFullInfo) GetRemarkSurname() *wrapperspb.StringValue {
	if x != nil {
		return x.RemarkSurname
	}
	return nil
}

type Contact struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerUserID    string                 `protobuf:"bytes,1,opt,name=ownerUserID,proto3" json:"ownerUserID,omitempty"`
	ContactUserID  string                 `protobuf:"bytes,2,opt,name=contactUserID,proto3" json:"contactUserID,omitempty"`
	CreateTime     int64                  `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	OperatorUserID string                 `protobuf:"bytes,4,opt,name=operatorUserID,proto3" json:"operatorUserID,omitempty"`
	Ex             string                 `protobuf:"bytes,5,opt,name=ex,proto3" json:"ex,omitempty"`
	Status         bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	IsBlock        bool                   `protobuf:"varint,7,opt,name=isBlock,proto3" json:"isBlock,omitempty"`
	RemarkName     string                 `protobuf:"bytes,8,opt,name=remarkName,proto3" json:"remarkName,omitempty"`
	RemarkSurname  string                 `protobuf:"bytes,9,opt,name=remarkSurname,proto3" json:"remarkSurname,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *Contact) GetOwnerUserID() string {
	if x != nil {
		return x.OwnerUserID
	}
	return ""
}

func (x *Contact) GetContactUserID() string {
	if x != nil {
		return x.ContactUserID
	}
	return ""
}

func (x *Contact) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Contact) GetOperatorUserID() string {
	if x != nil {
		return x.OperatorUserID
	}
	return ""
}

func (x *Contact) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *Contact) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Contact) GetIsBlock() bool {
	if x != nil {
		return x.IsBlock
	}
	return false
}

func (x *Contact) GetRemarkName() string {
	if x != nil {
		return x.RemarkName
	}
	return ""
}

func (x *Contact) GetRemarkSurname() string {
	if x != nil {
		return x.RemarkSurname
	}
	return ""
}

type UserPublicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	FaceURL       string                 `protobuf:"bytes,5,opt,name=faceURL,proto3" json:"faceURL,omitempty"`
	Gender        int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Level         int32                  `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	Surname       string                 `protobuf:"bytes,8,opt,name=surname,proto3" json:"surname,omitempty"`
	Name          string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPublicInfo) Reset() {
	*x = UserPublicInfo{}
	mi := &file_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPublicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPublicInfo) ProtoMessage() {}

func (x *UserPublicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPublicInfo.ProtoReflect.Descriptor instead.
func (*UserPublicInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *UserPublicInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserPublicInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserPublicInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserPublicInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserPublicInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *UserPublicInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserPublicInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserPublicInfo) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *UserPublicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	AreaCode      string                 `protobuf:"bytes,2,opt,name=areaCode,proto3" json:"areaCode,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	DeviceID      string                 `protobuf:"bytes,4,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Platform      int32                  `protobuf:"varint,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Account       string                 `protobuf:"bytes,6,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	mi := &file_common_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *UserIdentity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserIdentity) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *UserIdentity) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserIdentity) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *UserIdentity) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *UserIdentity) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type AppletInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AppID         string                 `protobuf:"bytes,3,opt,name=appID,proto3" json:"appID,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Md5           string                 `protobuf:"bytes,6,opt,name=md5,proto3" json:"md5,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	Priority      uint32                 `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	Status        uint32                 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    int64                  `protobuf:"varint,11,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppletInfo) Reset() {
	*x = AppletInfo{}
	mi := &file_common_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppletInfo) ProtoMessage() {}

func (x *AppletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppletInfo.ProtoReflect.Descriptor instead.
func (*AppletInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{5}
}

func (x *AppletInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppletInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppletInfo) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

func (x *AppletInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AppletInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AppletInfo) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *AppletInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AppletInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AppletInfo) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AppletInfo) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AppletInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type LogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Platform      int32                  `protobuf:"varint,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	LogID         string                 `protobuf:"bytes,6,opt,name=logID,proto3" json:"logID,omitempty"`
	Filename      string                 `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`
	SystemType    string                 `protobuf:"bytes,8,opt,name=systemType,proto3" json:"systemType,omitempty"`
	Ex            string                 `protobuf:"bytes,9,opt,name=ex,proto3" json:"ex,omitempty"`
	Version       string                 `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInfo) Reset() {
	*x = LogInfo{}
	mi := &file_common_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInfo) ProtoMessage() {}

func (x *LogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInfo.ProtoReflect.Descriptor instead.
func (*LogInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{6}
}

func (x *LogInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *LogInfo) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *LogInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LogInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *LogInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LogInfo) GetLogID() string {
	if x != nil {
		return x.LogID
	}
	return ""
}

func (x *LogInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *LogInfo) GetSystemType() string {
	if x != nil {
		return x.SystemType
	}
	return ""
}

func (x *LogInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *LogInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_common_common_proto protoreflect.FileDescriptor

const file_common_common_proto_rawDesc = "" +
	"\n" +
	"\x13common/common.proto\x12\x12openim.chat.common\x1a\x1bwrapperspb/wrapperspb.proto\"\xc0\x06\n" +
	"\fUserFullInfo\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12 \n" +
	"\vphoneNumber\x18\x04 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bareaCode\x18\x05 \x01(\tR\bareaCode\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\a \x01(\tR\bnickname\x12\x18\n" +
	"\afaceURL\x18\b \x01(\tR\afaceURL\x12\x16\n" +
	"\x06gender\x18\t \x01(\x05R\x06gender\x12\x14\n" +
	"\x05level\x18\n" +
	" \x01(\x05R\x05level\x12\x14\n" +
	"\x05birth\x18\v \x01(\x03R\x05birth\x12&\n" +
	"\x0eallowAddFriend\x18\f \x01(\x05R\x0eallowAddFriend\x12\x1c\n" +
	"\tallowBeep\x18\r \x01(\x05R\tallowBeep\x12&\n" +
	"\x0eallowVibration\x18\x0e \x01(\x05R\x0eallowVibration\x12*\n" +
	"\x10globalRecvMsgOpt\x18\x0f \x01(\x05R\x10globalRecvMsgOpt\x12\"\n" +
	"\fregisterType\x18\x10 \x01(\x05R\fregisterType\x12\x18\n" +
	"\asurName\x18\x11 \x01(\tR\asurName\x12\x12\n" +
	"\x04name\x18\x12 \x01(\tR\x04name\x12\x1c\n" +
	"\tqrcodeUrl\x18\x13 \x01(\tR\tqrcodeUrl\x12\x1c\n" +
	"\tpublicKey\x18\x14 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x15 \x01(\tR\aaddress\x12\x1c\n" +
	"\tisContact\x18\x16 \x01(\x05R\tisContact\x12\x1c\n" +
	"\tisBlocked\x18\x17 \x01(\x05R\tisBlocked\x12$\n" +
	"\rautoDeleteMsg\x18\x18 \x01(\x05R\rautoDeleteMsg\x12.\n" +
	"\x12autoDeleteDuration\x18\x19 \x01(\x05R\x12autoDeleteDuration\x12\"\n" +
	"\fonlineStatus\x18\x1a \x01(\x05R\fonlineStatus\x12\x1c\n" +
	"\tofflineAt\x18\x1b \x01(\x05R\tofflineAt\"\xee\x06\n" +
	"\x0fContactFullInfo\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12 \n" +
	"\vphoneNumber\x18\x04 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bareaCode\x18\x05 \x01(\tR\bareaCode\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\a \x01(\tR\bnickname\x12\x18\n" +
	"\afaceURL\x18\b \x01(\tR\afaceURL\x12\x16\n" +
	"\x06gender\x18\t \x01(\x05R\x06gender\x12\x14\n" +
	"\x05level\x18\n" +
	" \x01(\x05R\x05level\x12\x14\n" +
	"\x05birth\x18\v \x01(\x03R\x05birth\x12&\n" +
	"\x0eallowAddFriend\x18\f \x01(\x05R\x0eallowAddFriend\x12\x1c\n" +
	"\tallowBeep\x18\r \x01(\x05R\tallowBeep\x12&\n" +
	"\x0eallowVibration\x18\x0e \x01(\x05R\x0eallowVibration\x12*\n" +
	"\x10globalRecvMsgOpt\x18\x0f \x01(\x05R\x10globalRecvMsgOpt\x12\"\n" +
	"\fregisterType\x18\x10 \x01(\x05R\fregisterType\x12\x18\n" +
	"\asurName\x18\x11 \x01(\tR\asurName\x12\x12\n" +
	"\x04name\x18\x12 \x01(\tR\x04name\x12\x1c\n" +
	"\tqrcodeUrl\x18\x13 \x01(\tR\tqrcodeUrl\x12\x1c\n" +
	"\tpublicKey\x18\x14 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tisBlocked\x18\x15 \x01(\bR\tisBlocked\x12\x18\n" +
	"\aaddress\x18\x16 \x01(\tR\aaddress\x12\"\n" +
	"\fonlineStatus\x18\x17 \x01(\x05R\fonlineStatus\x129\n" +
	"\tofflineAt\x18\x18 \x01(\v2\x1b.openim.protobuf.Int32ValueR\tofflineAt\x12<\n" +
	"\n" +
	"remarkName\x18\x19 \x01(\v2\x1c.openim.protobuf.StringValueR\n" +
	"remarkName\x12B\n" +
	"\rremarkSurname\x18\x1a \x01(\v2\x1c.openim.protobuf.StringValueR\rremarkSurname\"\xa1\x02\n" +
	"\aContact\x12 \n" +
	"\vownerUserID\x18\x01 \x01(\tR\vownerUserID\x12$\n" +
	"\rcontactUserID\x18\x02 \x01(\tR\rcontactUserID\x12\x1e\n" +
	"\n" +
	"createTime\x18\x03 \x01(\x03R\n" +
	"createTime\x12&\n" +
	"\x0eoperatorUserID\x18\x04 \x01(\tR\x0eoperatorUserID\x12\x0e\n" +
	"\x02ex\x18\x05 \x01(\tR\x02ex\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\x12\x18\n" +
	"\aisBlock\x18\a \x01(\bR\aisBlock\x12\x1e\n" +
	"\n" +
	"remarkName\x18\b \x01(\tR\n" +
	"remarkName\x12$\n" +
	"\rremarkSurname\x18\t \x01(\tR\rremarkSurname\"\xea\x01\n" +
	"\x0eUserPublicInfo\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x18\n" +
	"\afaceURL\x18\x05 \x01(\tR\afaceURL\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12\x14\n" +
	"\x05level\x18\a \x01(\x05R\x05level\x12\x18\n" +
	"\asurname\x18\b \x01(\tR\asurname\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\"\xb4\x01\n" +
	"\fUserIdentity\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bareaCode\x18\x02 \x01(\tR\bareaCode\x12 \n" +
	"\vphoneNumber\x18\x03 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bdeviceID\x18\x04 \x01(\tR\bdeviceID\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\x05R\bplatform\x12\x18\n" +
	"\aaccount\x18\x06 \x01(\tR\aaccount\"\x80\x02\n" +
	"\n" +
	"AppletInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05appID\x18\x03 \x01(\tR\x05appID\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x10\n" +
	"\x03md5\x18\x06 \x01(\tR\x03md5\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12\x1a\n" +
	"\bpriority\x18\t \x01(\rR\bpriority\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\rR\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\v \x01(\x03R\n" +
	"createTime\"\x87\x02\n" +
	"\aLogInfo\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\x05R\bplatform\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x14\n" +
	"\x05logID\x18\x06 \x01(\tR\x05logID\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename\x12\x1e\n" +
	"\n" +
	"systemType\x18\b \x01(\tR\n" +
	"systemType\x12\x0e\n" +
	"\x02ex\x18\t \x01(\tR\x02ex\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\tR\aversionB,Z*github.com/SupersStone/chatprotocol/commonb\x06proto3"

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData []byte
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)))
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_common_proto_goTypes = []any{
	(*UserFullInfo)(nil),           // 0: openim.chat.common.UserFullInfo
	(*ContactFullInfo)(nil),        // 1: openim.chat.common.ContactFullInfo
	(*Contact)(nil),                // 2: openim.chat.common.Contact
	(*UserPublicInfo)(nil),         // 3: openim.chat.common.UserPublicInfo
	(*UserIdentity)(nil),           // 4: openim.chat.common.UserIdentity
	(*AppletInfo)(nil),             // 5: openim.chat.common.AppletInfo
	(*LogInfo)(nil),                // 6: openim.chat.common.LogInfo
	(*wrapperspb.Int32Value)(nil),  // 7: openim.protobuf.Int32Value
	(*wrapperspb.StringValue)(nil), // 8: openim.protobuf.StringValue
}
var file_common_common_proto_depIdxs = []int32{
	7, // 0: openim.chat.common.ContactFullInfo.offlineAt:type_name -> openim.protobuf.Int32Value
	8, // 1: openim.chat.common.ContactFullInfo.remarkName:type_name -> openim.protobuf.StringValue
	8, // 2: openim.chat.common.ContactFullInfo.remarkSurname:type_name -> openim.protobuf.StringValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
